"""initial

Revision ID: bdfca13e1bc6
Revises:
Create Date: 2026-06-07 20:26:07.989012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdfca13e1bc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('media_path', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media')),
    sa.UniqueConstraint('media_path', name=op.f('uq_media_media_path'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('tg_id', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', name='userrole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(phone IS NOT NULL) OR (email IS NOT NULL)', name=op.f('ck_users_`check_user_has_contact`')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone')),
    sa.UniqueConstraint('tg_id', name=op.f('uq_users_tg_id')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('cafes',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('photo_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['media.id'], name=op.f('fk_cafes_photo_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cafes')),
    sa.UniqueConstraint('name', 'address', 'phone', name='check_unique_name_address_phone')
    )
    op.create_table('bookings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('guest_number', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('BOOKING', 'ACTIVE', 'COMPLETED', 'CANCELED', name='bookingstatus'), nullable=False),
    sa.Column('note', sa.String(length=800), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('booking_date >= CURRENT_DATE', name=op.f('ck_bookings_`check_booking_date_is_not_past`')),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], name=op.f('fk_bookings_cafe_id_cafes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_table('managers_cafes',
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], name=op.f('fk_managers_cafes_cafe_id_cafes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_managers_cafes_manager_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manager_id', 'cafe_id', name=op.f('pk_managers_cafes'))
    )
    op.create_table('slots',
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_time < end_time', name=op.f('ck_slots_`check_slot_is_possible`')),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], name=op.f('fk_slots_cafe_id_cafes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slots'))
    )
    op.create_table('tables',
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('seat_number > 0', name=op.f('ck_tables_`check_table_seat_number_is_possible`')),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], name=op.f('fk_tables_cafe_id_cafes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tables'))
    )
    op.create_table('booking_table_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_table_slots_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_booking_table_slots_slot_id_slots')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_booking_table_slots_table_id_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_table_slots'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_table_slots')
    op.drop_table('tables')
    op.drop_table('slots')
    op.drop_table('managers_cafes')
    op.drop_table('bookings')
    op.drop_table('cafes')
    op.drop_table('users')
    op.drop_table('media')
    # ### end Alembic commands ###
