# -------------------------------
# Параметры подключения
# -------------------------------
max_connections = 1000
shared_buffers = 256MB
effective_cache_size = 768MB
maintenance_work_mem = 64MB
checkpoint_completion_target = 0.7
wal_buffers = 16MB
default_statistics_target = 100

# -------------------------------
# Дополнительные параметры
# -------------------------------
# Время ожидания контрольных точек (по умолчанию 5 минут)
checkpoint_timeout = 15min
# Включить сжатие WAL-логов для экономии места
wal_compression = on
# Логировать медленные запросы (дольше 500 мс) для отладки
log_min_duration_statement = 500
# Логировать контрольные точки, подключения и отключения
log_checkpoints = on
log_connections = on
log_disconnections = on
# Слушаем все интерфейсы, чтобы принять подключение от других контейнеров
listen_addresses = '*'
